services:
    material.materialy:
        class: Pjpl\MaterialBundle\Services\MaterialList
        arguments: [@service_container]
    material.grupa:
        class: Pjpl\MaterialBundle\Services\GrupaList
        arguments: [@service_container]
    material.jm:
        class: Pjpl\MaterialBundle\Services\JednostkaMiaryList
        arguments: [@service_container]
